### ISSUE TITLE
Issue with "_" in twitter handle

### ISSUE THREAD

**Issue by bryandmartin** [serrat839/mRkov#21]
If someone has an "_" in their twitter handle, it is causing issues. For example, if I retweet

"@a_b_c" I am sometimes getting just "@a" or "_b" in my output.

**Comment by serrat839** [comment]
Now that we use handle banks, this issue should be resolved. For now I will close it, but I will keep my eyes peeled for this issue again.

![image](https://user-images.githubusercontent.com/59586549/79527871-81e69280-801d-11ea-875a-e6da9239a2d2.png)

Attached is an example of the sentence generator handling "_" appropriately.
