### ISSUE TITLE
Spaces before hashtags

### ISSUE THREAD

**Issue by bryandmartin** [serrat839/mRkov#24]

**Comment by serrat839** [comment]
Do you remember what the issue with this one was? I'm looking at it and hashtags seem to be intact even if they have punctuation like "_" in them: 

![image](https://user-images.githubusercontent.com/59586549/79528456-d9d1c900-801e-11ea-91b1-ac4ded1e5448.png)

I think by fixing the way we are now handling our tweet slicing (turning ".,?!" into their own tokens) we fixed this problem.
Hashtags also have appropriate spacing before and after them. 
![image](https://user-images.githubusercontent.com/59586549/79528624-5795d480-801f-11ea-9243-974691e549ae.png)
