### ISSUE TITLE
Only retrieving 90 tweets?

### ISSUE THREAD

**Issue by bwiernik** [serrat839/mRkov#30]
When I run the Shiny app locally, it always reports only finding 90 tweets in the console. In the shiny app, it reports the larger number of tweets (e.g., 1926).

**Comment by bryandmartin** [comment]
Do you have the handle you are using that you would be willing to share so we can test this to try and identify the issue?

**Comment by serrat839** [comment]
In line 35 of tweet_gettr.R I accidentally used ncol() instead of nrow() to see tweets were actually scraped! Whoops!

**Comment by bryandmartin** [comment]
@serrat839 Nice job! Does this mean that the number actually scraped was correct, we are just printing the wrong amount?

**Comment by bryandmartin** [comment]
Also, this doesn't explain the difference between the server and local runs. I find that particularly odd
